---
title: "PG Veränderungen"
author: "grb"
date: "2023-02-13"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(ggalluvial)

pg <- read.csv('O:/U5279/Routinedaten/Abschlussdatenlieferung20_21/Daten/02_roh/04_vz_pg_20-21_2022-07-20 19-01-26.csv')
stamm <- read.csv('O:/U5279/Routinedaten/Abschlussdatenlieferung20_21/Daten/02_roh/01_stamm_20-21_2022-07-20 18-55-30.csv')
```

Datensatz vorbereiten: 
```{r}
# PG df prep
pg <- pg %>% 
  mutate(across(starts_with('V_PG_'), ~ ymd(.)))

# df mit Sterbedaten vorbereiten (gleiche Bauart wie PG-Tabelle herstellen)
tmp <- stamm %>%
  mutate(V_STERBEDATUM=ymd(V_STERBEDATUM)) %>% 
  na.omit() %>% 
  mutate(V_ID_PG = NA, 
         V_PFLEGEGRAD = 99,
         V_PG_BIS = as.Date('9999-12-31')) %>% 
  select(V_ID, V_ID_PG, V_PFLEGEGRAD, V_PG_VON = V_STERBEDATUM, V_PG_BIS)

# zusammenfügen & in Form bringen  
dat <- bind_rows(pg, tmp) %>% 
  group_by(V_ID) %>% 
  arrange(V_ID, V_PG_VON) %>%
  ungroup
```


Intervalle & Zeitreihe erstellen (Individualebene)
```{r}
# Intervalle erstellen
dat$int <- interval(start=dat$V_PG_VON, end=dat$V_PG_BIS)

# Welchen Pflegegrad hatten die Personen zu bestimmten Zeitpunkten von Start bis Ende des Datenzeitraums?
tmp <- dat %>%
  slice_head(n = 5000) %>%
  group_by(V_ID) %>%
  arrange(V_ID, V_PG_VON) %>%
  mutate(
    pg_Start = V_PFLEGEGRAD[as.Date('2020-01-01') %within% int],
    pg_Jul20 = ifelse(any(as.Date('2020-07-01') %within% int), V_PFLEGEGRAD[as.Date('2020-07-01') %within% int], pg_Start),
    pg_Jan21 = ifelse(any(as.Date('2021-01-01') %within% int), V_PFLEGEGRAD[as.Date('2021-01-01') %within% int], pg_Jul20),
    pg_Jul21 = ifelse(any(as.Date('2021-07-01') %within% int), V_PFLEGEGRAD[as.Date('2021-07-01') %within% int], pg_Jan21),
    pg_Ende = ifelse(any(as.Date('2021-12-31') %within% int), V_PFLEGEGRAD[as.Date('2021-12-31') %within% int], pg_Jul21)
  ) %>%
  ungroup() %>%
  distinct(V_ID, .keep_all = TRUE) %>%
  select(pg_Start:pg_Ende)
```


```{r}
# pivotieren & aggregieren
tmp2 <- tmp %>% 
  pivot_longer(pg_Start:pg_Ende, names_to = 'mzp', values_to = 'pg') %>%
  group_by(mzp, pg) %>% 
  tally() %>% 
  rename(freq = n) %>%
  mutate(mzp = factor(mzp, levels=c('pg_Start', 'pg_Jul20', 'pg_Jan21', 'pg_Jul21', 'pg_Ende')),
         pg = factor(pg)) %>% 
  complete(pg) %>% 
  replace_na(list(freq = 0)) %>% 
  ungroup() %>% 
  mutate(id = row_number())


# levels=c('PG1', 'PG2', 'PG3', 'PG4', 'PG5', 'Tot'))
# is_alluvia_form(as.data.frame(tmp2), axes = 1, silent = TRUE)
```
To do: visualisieren
```{r}

```



axis = horizontale Anordnung (versch. Zeitpunkte, mzp)
strata = Blocks der axis (pg-Kategorien)
alluvia = Wanderung, kann nochmal nach Gruppen gefüllt weden (auch pg)
flow = Segmente der Alluvia zwischen axis

alluvia format (wide)



